name: Lint & Test
# Thank you folke and apologies for pinching some of these but
# your CI for neovim plugins is impeccably set up and re-usable

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  stylua:
    name: Stylua Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua

  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1

  debug:
    name: Check for Debug Statements
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Debug
        run: |
          if /bin/grep --line-number -r -P '^(?!\s*--).*\bdd\(' --color=always lua; then
            echo "Debug messages found"
            exit 1
          else
            echo "No debug messages found"
          fi

  tests:
    runs-on: ubuntu-latest
    needs: config
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: folke/github/neovim@main
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libreadline-dev
      - name: Test Cache
        uses: actions/cache@v4
        with:
          path: .tests
          key: ${{ runner.os }}-tests-${{ hashFiles('tests/minit.lua', 'scripts/test') }}
      - name: Run Tests
        run: ./scripts/test
